version: '3.8'

networks:
  rbm:
    external:
      false

services:

  postgres-users:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - rbm
    ports:
      - 5433:5432

  postgres-houses:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - rbm
    ports:
      - 5434:5432

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - rbm
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres:
