-- AlterTable
ALTER TABLE "House" ADD COLUMN     "city" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "state" VARCHAR(2) NOT NULL DEFAULT '',
ADD COLUMN     "zipcode" VARCHAR(5) NOT NULL DEFAULT '',
ALTER COLUMN "beds" SET DEFAULT 1,
ALTER COLUMN "baths" SET DEFAULT 1,
ALTER COLUMN "workspace" SET DEFAULT 0;
